# Generated by Django 5.0.6 on 2024-08-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardId', models.IntegerField(max_length=4)),
                ('clockIn', models.DateTimeField(blank=True, null=True)),
                ('clockOut', models.DateTimeField(blank=True, null=True)),
                ('numberOfHours', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
