# Generated by Django 5.0.6 on 2024-08-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClockInSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockinlog',
            name='guardId',
            field=models.IntegerField(),
        ),
    ]
